# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: ddm\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2013-10-03 09:21+0200\n"
"PO-Revision-Date: 2014-06-26 09:36+0100\n"
"Last-Translator: \n"
"Language-Team: SolydXK <admin@solydxk.com>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Poedit 1.5.4\n"
"Language: Japanese\n"
"X-Poedit-SourceCharset: UTF-8\n"

#: usr/lib/ddm/ati.py:72
#, python-format
msgid "ATI card found: %(card)s"
msgstr "ATI カードが見つかりました: %(card)s"

#: usr/lib/ddm/ati.py:77
#, python-format
msgid "ATI chip serie found: %(serie)s"
msgstr "ATI チップシリーズが見つかりました: %(serie)s"

#: usr/lib/ddm/ati.py:86
#, python-format
msgid "ATI driver found: %(drv)s (%(status)s)"
msgstr "ATI ドライバーが見つかりました: %(drv)s (%(status)s)"

#: usr/lib/ddm/ati.py:89 usr/lib/ddm/intel.py:56 usr/lib/ddm/nvidia.py:104
#: usr/lib/ddm/via.py:55
#, python-format
msgid "Driver not installable: %(drv)s"
msgstr "ドライバーはインストールされていません: %(drv)s"

#: usr/lib/ddm/ati.py:91
#, python-format
msgid "ATI chip serie not supported: %(serie)d"
msgstr "ATI チップシリーズはサポートされていません: %(serie)d"

#: usr/lib/ddm/ati.py:93
#, python-format
msgid "No driver found for: %(card)s (%(man)s:%(serie)s)"
msgstr "ドライバーが見つかりません: %(card)s (%(man)s:%(serie)s)"

#: usr/lib/ddm/ati.py:106 usr/lib/ddm/intel.py:68 usr/lib/ddm/nvidia.py:118
#: usr/lib/ddm/via.py:67
#, python-format
msgid "Install driver: %(drv)s"
msgstr "ドライバーをインストール: %(drv)s"

#: usr/lib/ddm/ati.py:120 usr/lib/ddm/nvidia.py:137
#, python-format
msgid "Switch to module: %(module)s"
msgstr "モジュールを切り替え: %(module)s"

#: usr/lib/ddm/ati.py:126 usr/lib/ddm/intel.py:77 usr/lib/ddm/nvidia.py:147
#: usr/lib/ddm/via.py:76
#, python-format
msgid "Driver installed: %(drv)s"
msgstr "ドライバーをインストールしました: %(drv)s"

#: usr/lib/ddm/ati.py:137
msgid "Removing ATI drivers"
msgstr "ATI ドライバーの削除"

#: usr/lib/ddm/ati.py:151 usr/lib/ddm/intel.py:96 usr/lib/ddm/nvidia.py:176
#: usr/lib/ddm/via.py:95
#, python-format
msgid "Driver removed: %(drv)s"
msgstr "ドライバーを削除しました: %(drv)s"

#: usr/lib/ddm/ati.py:159
msgid "ATI display driver"
msgstr "ATI ディスプレイドライバー"

#: usr/lib/ddm/ati.py:161 usr/lib/ddm/intel.py:104 usr/lib/ddm/nvidia.py:186
msgid "Intel display driver"
msgstr "Intel ディスプレイドライバー"

#: usr/lib/ddm/ati.py:163
msgid "Radeon display driver"
msgstr "Radeon ディスプレイドライバー"

#: usr/lib/ddm/ati.py:165 usr/lib/ddm/intel.py:106 usr/lib/ddm/nvidia.py:190
#: usr/lib/ddm/via.py:105
msgid "Framebuffer display driver"
msgstr "フレームバッファディスプレイドライバー"

#: usr/lib/ddm/ati.py:167 usr/lib/ddm/intel.py:108 usr/lib/ddm/nvidia.py:192
#: usr/lib/ddm/via.py:107
msgid "Vesa display driver"
msgstr "VESA ディスプレイドライバー"

#: usr/lib/ddm/ati.py:230
#, python-format
msgid "Install aborted: not in repository: %(repo)s"
msgstr "インストールを中断: リボジトリにありません: %(repo)s"

#: usr/lib/ddm/broadcom.py:88
#, python-format
msgid "Broadcom chip serie found: %(chip)s"
msgstr "Broadcom チップシリーズが見つかりました: %(chip)s"

#: usr/lib/ddm/broadcom.py:157
#, python-format
msgid "Used wireless driver: %(drv)s"
msgstr "無線ドライバーを使用しました: %(drv)s"

#: usr/lib/ddm/broadcom.py:178
#, python-format
msgid "Broadcom found: %(broadcom)s"
msgstr "Broadcom を見つけました: %(broadcom)s"

#: usr/lib/ddm/broadcom.py:201
#, python-format
msgid "Broadcom chipset not supported or ethernet controller: %(broadcom)s"
msgstr ""
"Broadcom チップセットはサポートされていませんまたは有線 LAN コントローラで"
"す: %(broadcom)s"

#: usr/lib/ddm/broadcom.py:203
#, python-format
msgid "Broadcom chipset not found: %(chip)s"
msgstr "Broadcom チップセットが見つかりません: %(chip)s"

#: usr/lib/ddm/broadcom.py:206
#, python-format
msgid "Broadcom pci ID not found: %(id)s"
msgstr "Broadcom PCI ID が見つかりません: %(id)s"

#: usr/lib/ddm/broadcom.py:215
#, python-format
msgid "Linux header name to install: %(header)s"
msgstr "Linux ヘッダーへインストール: %(header)s"

#: usr/lib/ddm/broadcom.py:219
#, python-format
msgid "Download package: %(package)s"
msgstr "パッケージをダウンロード: %(package)s"

#: usr/lib/ddm/broadcom.py:227
#, python-format
msgid "Download package: %(drv)s"
msgstr "パッケージをダウンロード: %(drv)s"

#: usr/lib/ddm/broadcom.py:264
msgid "Install downloaded packages"
msgstr "ダウンロードしたパッケージのインストール"

#: usr/lib/ddm/broadcom.py:272
#, python-format
msgid "Reconfigure package: %(package)s"
msgstr "パッケージの再設定: %(package)s"

#: usr/lib/ddm/broadcom.py:315
#, python-format
msgid "Purge driver: %(drv)s"
msgstr "ドライバーの排除: %(drv)s"

#: usr/lib/ddm/broadcom.py:325
msgid "Done removing Broadcom drivers"
msgstr "Broadcom ドライバーの削除を行いました"

#: usr/lib/ddm/ddm.py:81
msgid "Graphics"
msgstr "グラフィック"

#: usr/lib/ddm/ddm.py:82
msgid "Wireless"
msgstr "無線"

#: usr/lib/ddm/ddm.py:83
msgid "Kernel"
msgstr "カーネル"

#: usr/lib/ddm/ddm.py:84
msgid "Hardware"
msgstr "ハードウェア"

#: usr/lib/ddm/ddm.py:85
msgid "Activated driver"
msgstr "稼働しているドライバー"

#: usr/lib/ddm/ddm.py:86
msgid "Alternative drivers"
msgstr "代わりのドライバー"

#: usr/lib/ddm/ddm.py:167 usr/lib/ddm/ddm.py:198
msgid "Current drivers are correct"
msgstr "現在のドライバーを修正"

#: usr/lib/ddm/ddm.py:208
msgid "PAE already installed"
msgstr "PAE はすでにインストールされています"

#: usr/lib/ddm/ddm.py:210
msgid "PAE support only for 32-bit systems"
msgstr "PAE 対応は 32 ビットシステムのみです"

#: usr/lib/ddm/ddm.py:250
msgid "Activate"
msgstr "稼働"

#: usr/lib/ddm/ddm.py:250
msgid "Driver"
msgstr "ドライバー"

#: usr/lib/ddm/ddm.py:250
msgid "Version"
msgstr "バージョン"

#: usr/lib/ddm/ddm.py:250
msgid "Description"
msgstr "説明"

#: usr/lib/ddm/ddm.py:265
msgid " (recommended)"
msgstr " (推奨)"

#: usr/lib/ddm/ddm.py:310
msgid "Unknown driver"
msgstr "不明なドライバー"

#: usr/lib/ddm/ddm.py:313
msgid ""
"Unknown driver found.\n"
"\n"
"Please remove before installing drivers with DDM."
msgstr ""
"不明なドライバーが見つかりました\n"
"\n"
"インストールの前に取り除いて下さい。"

#: usr/lib/ddm/ddm.py:358
msgid "Driver activation"
msgstr "ドライバーの有効化"

#: usr/lib/ddm/ddm.py:358
#, python-format
msgid ""
"Are you sure you want to install the following driver:\n"
"\n"
"%(drv)s"
msgstr ""
"以下のドライバーをインストールしますか？:\n"
"\n"
"%(drv)s"

#: usr/lib/ddm/ddm.py:363 usr/lib/ddm/ddm.py:503
msgid "Locked"
msgstr "ロック"

#: usr/lib/ddm/ddm.py:363
#, python-format
msgid ""
"Could not get lock on %(file)s.\n"
"\n"
"Close any programs locking the file and try again."
msgstr ""
"%(file)s がロックされています。\n"
"\n"
"ロックしているプログラムを閉じ、再度行って下さい。"

#: usr/lib/ddm/ddm.py:441
msgid "Driver installed"
msgstr "ドライバーをインストールしました"

#: usr/lib/ddm/ddm.py:441
#, python-format
msgid ""
"Driver installed: %(drv)s\n"
"\n"
"Drivers will be used on next boot.\n"
"Do you want to reboot now?"
msgstr ""
"ドライバーをインストールしました: %(drv)s\n"
"\n"
"ドライバーは再起動後有効になります。\n"
"再起動しますか？"

#: usr/lib/ddm/ddm.py:503
#, python-format
msgid ""
"Could not get lock on %(file)s.\n"
"\n"
"Close any programs locking the file and restart DDM."
msgstr ""
"%(file)s がロックされています。\n"
"\n"
"ロックしているプログラムを閉じ、DDM を再起動して下さい。"

#: usr/lib/ddm/ddm.py:554
msgid "Checking your hardware..."
msgstr "ハードウェアを確認中..."

#: usr/lib/ddm/ddm.py:619
msgid "Start automatic driver install"
msgstr "自動ドライバーインストールの開始"

#: usr/lib/ddm/intel.py:47
#, python-format
msgid "Intel card found: %(card)s"
msgstr "Intel カードが見つかりました: %(card)s"

#: usr/lib/ddm/intel.py:53
#, python-format
msgid "Intel driver found: %(drv)s (%(status)s)"
msgstr "Intel ドライバが見つかりました: %(drv)s (%(status)s)"

#: usr/lib/ddm/main.py:66
#, python-format
msgid "Write debug information to file: %(path)s"
msgstr "デバック情報をファイルに書込: %(path)s"

#: usr/lib/ddm/main.py:70
#, python-format
msgid "Machine info: %(info)s"
msgstr "マシン情報: %(info)s"

#: usr/lib/ddm/main.py:72
#, python-format
msgid "DDM version: %(version)s"
msgstr "DDM バージョン: %(version)s"

#: usr/lib/ddm/main.py:77
msgid "apt-listbugs is installed and might interfere with driver installation"
msgstr ""
"apt-listbug インストールされ、ドライバーインストールに影響があるかもしれませ"
"ん"

#: usr/lib/ddm/main.py:107 usr/lib/ddm/main.py:109
msgid "Please enter your password"
msgstr "パスワードを入力して下さい"

#: usr/lib/ddm/main.py:115
msgid "DDM - Kernel"
msgstr "DDM - Kernel"

#: usr/lib/ddm/main.py:116
msgid ""
"You do not have the latest kernel installed.\n"
"\n"
"Use the Update Manager to update your system."
msgstr ""
"最新カーネルはインストールされていません\n"
"\n"
"アップデートマネージャーでシステムを更新して下さい。"

#: usr/lib/ddm/main.py:120
msgid "DDM - Live environment"
msgstr "DDM - Live environment"

#: usr/lib/ddm/main.py:121
msgid ""
"DDM cannot run in a live environment\n"
"\n"
"To force start, use the --force argument"
msgstr ""
"DDM を Live environment で動作することができません\n"
"\n"
"強制開始する場合は --force を使用して下さい"

#: usr/lib/ddm/main.py:125
msgid "DDM - Debian based"
msgstr "DDM - Debian ベース"

#: usr/lib/ddm/main.py:126
msgid ""
"Cannot determine the base distribution (debian or ubuntu)\n"
"\n"
"To force start, use the --force argument"
msgstr ""
"ディストリビューションベースを決定できません (Debian・Ubuntu)\n"
"\n"
"強制開始する場合は --force を使用して下さい"

#: usr/lib/ddm/main.py:130
msgid "DDM - Internet"
msgstr "DDM - インターネット"

#: usr/lib/ddm/main.py:131
msgid ""
"You do not seem to have an internet connection\n"
"\n"
"To force start, use the --force argument"
msgstr ""
"インターネットに接続していません\n"
"\n"
"強制開始する場合は --force を使用して下さい"

#: usr/lib/ddm/nvidia.py:56
msgid "Update apt"
msgstr "apt の更新"

#: usr/lib/ddm/nvidia.py:59
msgid "Install nvidia-detect"
msgstr "nvidia-detect インストール"

#: usr/lib/ddm/nvidia.py:67
msgid "Cannot install nvidia-detect: abort"
msgstr "nvidia-detect をインストールできません: 中止"

#: usr/lib/ddm/nvidia.py:91
#, python-format
msgid "Nvidia card found: %(card)s"
msgstr "Nvidia カードが見つかりました: %(card)s"

#: usr/lib/ddm/nvidia.py:101
#, python-format
msgid "Nvidia driver found: %(drv)s (%(status)s)"
msgstr "Nvidia ドライバーが見つかりました: %(drv)s (%(status)s)"

#: usr/lib/ddm/nvidia.py:159
msgid "Removing Nvidia drivers"
msgstr "Nvidia ドライバーの削除中"

#: usr/lib/ddm/nvidia.py:184
msgid "Nvidia display driver"
msgstr "Nvidia ディスプレイドライバー"

#: usr/lib/ddm/nvidia.py:188
msgid "Nouveau display driver"
msgstr "Nouveau ディスプレイドライバー"

#: usr/lib/ddm/pae.py:42
#, python-format
msgid "Installed PAE: %(pae)s"
msgstr "PAE をインストールしました: %(pae)s"

#: usr/lib/ddm/pae.py:48
msgid "Multi-core support for 32-bit systems"
msgstr "Multi-core の対応は 32 ビットシステムです"

#: usr/lib/ddm/pae.py:58
#, python-format
msgid "Multi-core already installed: %(package)s"
msgstr "Multi-core すでにイントールされています: %(package)s"

#: usr/lib/ddm/pae.py:59 usr/lib/ddm/pae.py:72
msgid "PAE capable system"
msgstr "PAE が使用できるシステム"

#: usr/lib/ddm/pae.py:65
msgid "Multi-core system running single-core kernel found"
msgstr ""

#: usr/lib/ddm/pae.py:69
msgid "PAE not installed"
msgstr "PAE をインストールできません"

#: usr/lib/ddm/pae.py:78
msgid "PAE kernel cannot be installed: single-core system"
msgstr "PAR カーネルをインストールできません: シングルコアシステム"

#: usr/lib/ddm/pae.py:94
msgid "Done installing PAE"
msgstr "PAE インストール完了"

#: usr/lib/ddm/pae.py:108
#, python-format
msgid "PAE package to remove: %(package)s"
msgstr "PAE パッケージの削除: %(package)s"

#: usr/lib/ddm/pae.py:111
msgid "Done removing PAE"
msgstr "PAE を削除しました"

#: usr/lib/ddm/pae.py:113
msgid "Cannot remove PAE when running PAE"
msgstr "PAE で動作しているため、PAE を削除できません"

#: usr/lib/ddm/via.py:46
#, python-format
msgid "Via card found: %(card)s"
msgstr "カードが見つかりました: %(card)s"

#: usr/lib/ddm/via.py:52
#, python-format
msgid "Via driver found: %(drv)s (%(status)s)"
msgstr "ドライバーが見つかりました: %(drv)s (%(status)s)"

#: usr/lib/ddm/via.py:103
msgid "Chrome display driver"
msgstr "Chrome ディスプレイドライバー"

#: usr/lib/ddm/xorg.py:78
#, python-format
msgid "Used graphics driver: %(module)s"
msgstr "使用しているグラフィックドライバー: %(module)s"

#: usr/lib/ddm/xorg.py:100
msgid "No xorg.conf - create minimal xorg.conf"
msgstr "xorg.conf なし - 最小限の xorg.conf を作成します"

#: usr/lib/ddm/xorg.py:120
msgid "New xorg.conf written"
msgstr "新たな xorg.conf の書き込み"

#: usr/lib/ddm/xorg.py:126
msgid "New section appended to xorg.conf"
msgstr "新しいセクションを xorg.conf に追加します"
